import { Link } from "react-router-dom";

function Terms() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto max-w-4xl px-6 py-12">
        <Link
          to="/"
          className="mb-8 inline-flex text-sm text-blue-400 hover:text-blue-300"
        >
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-bold">
          Terms of Service
        </h1>

        <p className="mt-3 text-sm text-slate-400">
          Last updated: September 19, 2026
        </p>

        <div className="mt-10 space-y-8 text-slate-300 leading-7">
          <section>
            <h2 className="text-2xl font-semibold text-white">
              1. Acceptance of Terms
            </h2>

            <p className="mt-3">
              By accessing or using CareerPilot AI, you
              agree to these Terms of Service. If you do
              not agree with these terms, please do not use
              the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              2. Description of Service
            </h2>

            <p className="mt-3">
              CareerPilot AI provides AI-powered career
              guidance and tools, including resume analysis,
              interview practice, career planning,
              LinkedIn optimization, and job opportunity
              discovery.
            </p>

            <p className="mt-3">
              CareerPilot AI provides informational and
              educational assistance. Results generated by
              AI may contain errors and should be reviewed
              before being relied upon for important career
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              3. User Accounts
            </h2>

            <p className="mt-3">
              You are responsible for providing accurate
              information and maintaining the security of
              your account. You are responsible for activity
              performed through your account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              4. Subscriptions and Payments
            </h2>

            <p className="mt-3">
              CareerPilot AI may offer paid subscription
              plans. Current subscription pricing may
              include a monthly plan of $5 and a yearly plan
              of $50.
            </p>

            <p className="mt-3">
              Payments and subscription billing are
              processed through Paddle. By purchasing a
              subscription, you agree to the applicable
              payment and billing terms presented during
              checkout.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              5. Subscription Cancellation
            </h2>

            <p className="mt-3">
              You may cancel your subscription according to
              the cancellation options provided through the
              payment and subscription system. Cancellation
              does not necessarily result in an immediate
              refund. Refund eligibility is governed by our
              Refund & Cancellation Policy and applicable
              requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              6. Acceptable Use
            </h2>

            <p className="mt-3">
              You agree not to misuse CareerPilot AI,
              interfere with its operation, attempt to gain
              unauthorized access, or use the service for
              unlawful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              7. Intellectual Property
            </h2>

            <p className="mt-3">
              CareerPilot AI and its associated software,
              design, branding, and original content are
              protected by applicable intellectual property
              laws. You may not reproduce or redistribute
              the service without authorization.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              8. Disclaimer
            </h2>

            <p className="mt-3">
              CareerPilot AI does not guarantee employment,
              interviews, job offers, or specific career
              outcomes. AI-generated recommendations are
              provided for informational purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              9. Limitation of Liability
            </h2>

            <p className="mt-3">
              To the extent permitted by applicable law,
              CareerPilot AI is not responsible for losses
              resulting from reliance on AI-generated
              information, service interruptions, or
              circumstances outside reasonable control.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              10. Changes to These Terms
            </h2>

            <p className="mt-3">
              We may update these Terms of Service from time
              to time. Updated terms will be published on
              this page with a revised update date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white">
              11. Contact
            </h2>

            <p className="mt-3">
              If you have questions about these Terms of
              Service, please contact CareerPilot AI through
              the Contact page.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

export default Terms;